services:
  php:
    build:
      context: ./php
    container_name: menejemen-kursus-online_php
    healthcheck:
      test: ["CMD-SHELL", "php artisan --version"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ./src:/var/www/html
    environment:
      - PROJECT_NAME=menejemen-kursus-online
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: menejemen-kursus-online_nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -k -fsSL https://menejemen-kursus-online.test || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - php

  db:
    image: mariadb:10.11
    container_name: menejemen-kursus-online_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: menejemen-kursus-online
      MYSQL_ROOT_PASSWORD: p455w0rd
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
